// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NGK_LAB10_WebAPI.Data;

namespace NGK_LAB10_WebAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20191111103739_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("NGK_LAB10_WebAPI.Models.Location", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<double>("Latitude")
                        .HasColumnType("float");

                    b.Property<double>("Longitude")
                        .HasColumnType("float");

                    b.HasKey("Name");

                    b.ToTable("Location");
                });

            modelBuilder.Entity("NGK_LAB10_WebAPI.Models.WeatherObservation", b =>
                {
                    b.Property<int>("WeatherObservationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("AirPressure")
                        .HasColumnType("decimal(10,1)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("Humidity")
                        .HasColumnType("int");

                    b.Property<string>("LocationName")
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("TemperatureC")
                        .HasColumnType("decimal(10,1)");

                    b.HasKey("WeatherObservationId");

                    b.HasIndex("LocationName");

                    b.ToTable("WeatherObservation");
                });

            modelBuilder.Entity("NGK_LAB10_WebAPI.Models.WeatherObservation", b =>
                {
                    b.HasOne("NGK_LAB10_WebAPI.Models.Location", "Location")
                        .WithMany()
                        .HasForeignKey("LocationName");
                });
#pragma warning restore 612, 618
        }
    }
}
